version: '3.8'
services:
  spring_jpa_cache:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/springdb
      - SPRING_DATASOURCE_USERNAME=mft
      - SPRING_DATASOURCE_PASSWORD=mft123
    restart: on-failure

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=springdb
      - POSTGRES_USER=mft
      - POSTGRES_PASSWORD=mft123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mft -d springdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data: