# Common application settings
spring:
  application:
    name: spring_jpa_cache
  profiles:
    active: dev  # Default profile (can be overridden with --spring.profiles.active)

  web:
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

# Production profile (PostgreSQL)
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/springdb1
    username: mft
    password: mft123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10        # Max connections in pool
      connection-timeout: 30000    # 30 seconds timeout
      initialization-fail-timeout: 0  # No fail on init
  jpa:
    hibernate:
      ddl-auto: update           # Update schema in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50          # Batch size for performance
  cache:
    type: simple                 # Simple in-memory cache
  h2:
    console:
      enabled: false             # Disable H2 console in prod

# Development/Testing profile (H2)
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:springdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop      # Recreate schema for dev/testing
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  cache:
    type: simple                 # Simple in-memory cache
  h2:
    console:
      enabled: true              # Enable H2 console for dev
      path: /h2-console

# Common server and security settings
server:
  port: 8443                     # HTTPS port
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: java123
    key-alias: myalias
    key-store-type: JKS
  servlet:
    session:
      timeout: 15m               # Session timeout after 15 minutes
      cookie:
        http-only: true          # Prevent JS access to cookies
        secure: true             # Only over HTTPS
        same-site: strict        # Prevent CSRF via cross-site requests

# Management endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus  # Expose useful endpoints

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Debug Spring Security
    org.hibernate.SQL: DEBUG            # Show SQL queries
    org.hibernate.orm.jdbc.bind: TRACE  # Show parameter binding
    org.hibernate.orm.jdbc.extract: TRACE  # Show result extraction
    org.hibernate.engine.transaction: DEBUG  # Transaction details
    com.zaxxer.hikari: DEBUG           # HikariCP pool details
    org.springframework.jdbc: DEBUG    # JDBC operations
    org.springframework.transaction: DEBUG  # Transaction management
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
